CREATE TABLE feedback (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source TEXT NOT NULL,
  content TEXT NOT NULL,
  sentiment TEXT NOT NULL,
  theme TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
